"""
Authentication commands for WAPI CLI

Handles login, logout, and authentication testing.
"""

import sys
import os
from pathlib import Path
from getpass import getpass
from typing import Optional
from ..api.client import WedosAPIClient
from ..config import load_config, get_config, validate_config
from ..constants import EXIT_SUCCESS, EXIT_ERROR, EXIT_AUTH_ERROR, EXIT_CONFIG_ERROR
from ..exceptions import (
    WAPIAuthenticationError,
    WAPIConfigurationError,
    WAPIConnectionError,
    WAPIRequestError,
    WAPIValidationError,
)
from ..utils.formatters import format_output
from ..utils.logger import get_logger


def cmd_auth_login(args, client: Optional[WedosAPIClient] = None) -> int:
    """Handle auth login command - interactive login"""
    logger = get_logger('commands.auth')
    logger.info("Starting interactive login")
    
    config_file = Path(args.config)
    
    # Get username
    if args.username:
        username = args.username
        logger.debug("Username provided via argument")
    else:
        # Interactive input
        print("WEDOS WAPI Login")
        print("=" * 50)
        username = input("Username (email): ").strip()
        if not username:
            logger.error("Username cannot be empty")
            print("Error: Username cannot be empty", file=sys.stderr)
            return EXIT_ERROR
    
    # Get password
    if args.password:
        password = args.password
        logger.debug("Password provided via argument")
    else:
        # Interactive input (hidden)
        password = getpass("WAPI Password: ")
        if not password:
            logger.error("Password cannot be empty")
            print("Error: Password cannot be empty", file=sys.stderr)
            return EXIT_ERROR
    
    # Validate credentials format
    from ..api.auth import validate_credentials
    is_valid, error = validate_credentials(username, password)
    if not is_valid:
        logger.warning(f"Invalid credential format: {error}")
        print(f"Error: {error}", file=sys.stderr)
        raise WAPIValidationError(error)
    
    # Test connection with provided credentials
    logger.info("Testing credentials with WAPI")
    print("Testing connection...")
    
    try:
        test_client = WedosAPIClient(username, password, use_json=False)
        result = test_client.ping()
        response = result.get('response', {})
        code = response.get('code')
        
        if code not in ['1000', 1000]:
            error_msg = response.get('result', 'Unknown error')
            logger.error(f"Authentication failed: {error_msg} (code: {code})")
            print(f"❌ Authentication failed: {error_msg}", file=sys.stderr)
            raise WAPIAuthenticationError(f"Authentication failed: {error_msg}")
        
        logger.info("Credentials validated successfully")
        print("✅ Connection successful")
    except (WAPIConnectionError, WAPIRequestError) as e:
        logger.error(f"Connection test failed: {e}")
        print(f"❌ Connection test failed: {e}", file=sys.stderr)
        raise
    except Exception as e:
        logger.error(f"Unexpected error during connection test: {e}")
        print(f"❌ Connection test failed: {e}", file=sys.stderr)
        raise WAPIConnectionError(f"Connection test failed: {e}") from e
    
    # Save credentials to config file
    logger.info(f"Saving credentials to {config_file}")
    
    # Read existing config
    config = {}
    if config_file.exists():
        try:
            with open(config_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        config[key] = value.strip().strip('"').strip("'")
        except Exception as e:
            logger.warning(f"Could not read existing config: {e}")
    
    # Update credentials
    config['WAPI_USERNAME'] = username
    config['WAPI_PASSWORD'] = password
    
    # Write back to file
    try:
        # Create directory if needed
        config_file.parent.mkdir(parents=True, exist_ok=True)
        
        with open(config_file, 'w', encoding='utf-8') as f:
            f.write("# WAPI Configuration\n")
            f.write("# Generated by 'wapi auth login'\n")
            f.write("# DO NOT commit this file to version control\n\n")
            
            for key, value in sorted(config.items()):
                if 'PASSWORD' in key.upper():
                    f.write(f'{key}="{value}"\n')
                else:
                    f.write(f'{key}="{value}"\n')
        
        # Set secure permissions
        os.chmod(config_file, 0o600)
        
        logger.info("Credentials saved successfully")
        print(f"✅ Credentials saved to {config_file}")
        print(f"   Username: {username}")
        print(f"   Password: {'*' * len(password)}")
        
        return EXIT_SUCCESS
    except (IOError, OSError, PermissionError) as e:
        logger.error(f"Failed to save credentials: {e}")
        print(f"Error: Could not save credentials: {e}", file=sys.stderr)
        raise WAPIConfigurationError(f"Cannot write to config file {config_file}: {e}") from e
    except Exception as e:
        logger.error(f"Unexpected error saving credentials: {e}")
        print(f"Error: Could not save credentials: {e}", file=sys.stderr)
        return EXIT_ERROR


def cmd_auth_logout(args, client: Optional[WedosAPIClient] = None) -> int:
    """Handle auth logout command - remove credentials"""
    logger = get_logger('commands.auth')
    logger.info("Logging out (removing credentials)")
    
    config_file = Path(args.config)
    
    if not config_file.exists():
        logger.warning(f"Config file does not exist: {config_file}")
        print(f"⚠️  Config file {config_file} does not exist", file=sys.stderr)
        return EXIT_SUCCESS
    
    # Read existing config
    config = {}
    try:
        with open(config_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    config[key] = value.strip().strip('"').strip("'")
    except Exception as e:
        logger.error(f"Could not read config file: {e}")
        print(f"Error: Could not read config file: {e}", file=sys.stderr)
        raise WAPIConfigurationError(f"Cannot read config file {config_file}: {e}") from e
    
    # Remove credentials
    if 'WAPI_USERNAME' in config:
        del config['WAPI_USERNAME']
    if 'WAPI_PASSWORD' in config:
        del config['WAPI_PASSWORD']
    
    # Write back (without credentials)
    try:
        with open(config_file, 'w', encoding='utf-8') as f:
            f.write("# WAPI Configuration\n")
            f.write("# Credentials removed by 'wapi auth logout'\n\n")
            
            for key, value in sorted(config.items()):
                f.write(f'{key}="{value}"\n')
        
        logger.info("Credentials removed successfully")
        print(f"✅ Credentials removed from {config_file}")
        return EXIT_SUCCESS
    except (IOError, OSError, PermissionError) as e:
        logger.error(f"Failed to remove credentials: {e}")
        print(f"Error: Could not update config file: {e}", file=sys.stderr)
        raise WAPIConfigurationError(f"Cannot write to config file {config_file}: {e}") from e
    except Exception as e:
        logger.error(f"Unexpected error removing credentials: {e}")
        print(f"Error: Could not update config file: {e}", file=sys.stderr)
        return EXIT_ERROR


def cmd_auth_status(args, client: Optional[WedosAPIClient] = None) -> int:
    """Handle auth status command - show authentication status"""
    logger = get_logger('commands.auth')
    logger.info("Checking authentication status")
    
    # Check if credentials exist
    username = get_config('WAPI_USERNAME', config_file=args.config)
    password = get_config('WAPI_PASSWORD', config_file=args.config)
    
    status_data = {
        'configured': bool(username and password),
        'username': username[:10] + '...' if username and len(username) > 10 else username or 'Not set',
        'password_set': bool(password),
        'config_file': str(args.config)
    }
    
    if not username or not password:
        logger.warning("Credentials not configured")
        print("⚠️  Not logged in")
        print(format_output(status_data, args.format))
        print("\nTo login, run: wapi auth login", file=sys.stderr)
        return EXIT_AUTH_ERROR
    
    # Test connection
    logger.debug("Testing connection with configured credentials")
    try:
        test_client = WedosAPIClient(username, password, use_json=False)
        result = test_client.ping()
        response = result.get('response', {})
        code = response.get('code')
        
        if code in ['1000', 1000]:
            status_data['connection'] = 'OK'
            status_data['authenticated'] = True
            logger.info("Authentication status: OK")
            print("✅ Logged in and authenticated")
        else:
            status_data['connection'] = 'Failed'
            status_data['authenticated'] = False
            error_msg = response.get('result', 'Unknown error')
            logger.warning(f"Authentication test failed: {error_msg}")
            print(f"⚠️  Logged in but authentication test failed: {error_msg}")
            status_data['error'] = error_msg
    except (WAPIConnectionError, WAPIRequestError) as e:
        logger.error(f"Failed to test authentication: {e}")
        status_data['connection'] = 'Error'
        status_data['authenticated'] = False
        status_data['error'] = str(e)
        print(f"❌ Error testing authentication: {e}", file=sys.stderr)
    
    print(format_output(status_data, args.format))
    return EXIT_SUCCESS if status_data.get('authenticated') else EXIT_AUTH_ERROR
