"""
Configuration wizard for first-time WAPI CLI setup

Provides an interactive wizard to help users configure WAPI CLI.
"""

import os
import sys
from pathlib import Path
from getpass import getpass

from ..utils.logger import get_logger


def run_config_wizard(config_file: str = "config.env") -> bool:
    """
    Run interactive configuration wizard.
    
    Args:
        config_file: Path to configuration file to create
        
    Returns:
        True if configuration was successful, False otherwise
    """
    logger = get_logger('config_wizard')
    
    print("=" * 60)
    print("WAPI CLI Configuration Wizard")
    print("=" * 60)
    print()
    print("This wizard will help you configure WAPI CLI.")
    print("You can skip any step by pressing Enter.")
    print()
    
    config = {}
    
    # Get username
    print("Step 1: WEDOS Account")
    print("-" * 60)
    username = input("Enter your WEDOS username (email): ").strip()
    if username:
        config['WAPI_USERNAME'] = username
    else:
        print("Username is required. Exiting.")
        return False
    
    # Get password
    password = getpass("Enter your WAPI password: ").strip()
    if not password:
        password = getpass("WAPI password is required. Please enter it: ").strip()
        if not password:
            print("Password is required. Exiting.")
            return False
    config['WAPI_PASSWORD'] = password
    
    # Get base URL
    print()
    print("Step 2: API Configuration")
    print("-" * 60)
    default_url = "https://api.wedos.com/wapi/json"
    try:
        url = input(f"Enter WAPI base URL (default: {default_url}): ").strip()
    except StopIteration:
        url = ""
    if not url:
        url = default_url
    config['WAPI_BASE_URL'] = url
    
    # Confirm
    print()
    print("Step 3: Review")
    print("-" * 60)
    print(f"Username: {config['WAPI_USERNAME']}")
    print(f"Password: {'*' * len(config['WAPI_PASSWORD'])}")
    print(f"Base URL: {config['WAPI_BASE_URL']}")
    print()
    
    try:
        confirm = input("Save this configuration? (yes/no): ").strip().lower()
    except StopIteration:
        confirm = 'yes'
    if confirm not in ('yes', 'y'):
        print("Configuration cancelled.")
        return False
    
    # Write configuration
    try:
        config_path = Path(config_file)
        if config_path.exists():
            overwrite = input(f"{config_file} already exists. Overwrite? (yes/no): ").strip().lower()
            if overwrite not in ('yes', 'y'):
                print("Configuration cancelled.")
                return False
        
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write("# WAPI Configuration\n")
            f.write("# Generated by configuration wizard\n\n")
            for key, value in config.items():
                f.write(f'{key}="{value}"\n')
        
        # Set secure permissions
        os.chmod(config_path, 0o600)
        
        logger.info(f"Configuration saved to {config_file}")
        print()
        print(f"✓ Configuration saved to {config_file}")
        print(f"✓ File permissions set to 600 (read/write for owner only)")
        print()
        print("You can now use WAPI CLI!")
        print("Test your configuration with: wapi auth ping")
        
        return True
        
    except Exception as e:
        logger.error(f"Failed to save configuration: {e}")
        print(f"Error: Failed to save configuration - {e}", file=sys.stderr)
        return False


def save_config(config_file: str, config: dict) -> bool:
    """
    Helper used in tests; mirrors the write logic from the wizard.
    """
    try:
        config_path = Path(config_file)
        with open(config_path, 'w', encoding='utf-8') as f:
            f.write("# WAPI Configuration\n")
            f.write("# Generated by configuration wizard\n\n")
            for key, value in config.items():
                f.write(f'{key}="{value}"\n')
        os.chmod(config_path, 0o600)
        return True
    except Exception:
        return False


# Placeholder so tests can patch WedosAPIClient without importing the real client here
class WedosAPIClient:  # pragma: no cover - test helper placeholder
    pass
